apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: dev-zookeeper
  name: dev-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      service: dev-zookeeper
  strategy: {}
  template:
    metadata:
      labels:
        network/kafka-network: "true"
        service: dev-zookeeper
    spec:
      containers:
        - env:
            - name: TZ
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_DATA_DIR
              value: "/var/lib/zookeeper/data"
            - name: ZOOKEEPER_LOG_DIR
              value: "/var/lib/zookeeper/log"
            - name: ZOOKEEPER_SERVER_ID
              value: "1"
          image: docker.io/confluentinc/cp-zookeeper:7.6.4
          name: zookeeper
          ports:
            - containerPort: 2181
          resources: {}
      hostname: dev-zookeeper
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: dev-kafka
  name: dev-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      service: dev-kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        network/kafka-network: "true"
        service: dev-kafka
    spec:
      enableServiceLinks: false
      containers:
      - name: kafka
        imagePullPolicy: IfNotPresent
        image: docker.io/confluentinc/cp-kafka:7.6.4
        ports:
          - containerPort: 29092
          - containerPort: 9092
        env:
          - name: CONFLUENT_SUPPORT_CUSTOMER_ID
            value: "anonymous"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "INTERNAL://dev-kafka:29092,LISTENER_EXTERNAL://dev-kafka:9092"
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_DEFAULT_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: "INTERNAL"
          - name: KAFKA_LISTENERS
            value: "INTERNAL://:29092,LISTENER_EXTERNAL://:9092"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: "INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT"
          - name: KAFKA_NUM_PARTITIONS
            value: "1"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_LOG_CLEANUP_POLICY
            value: "delete"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "dev-zookeeper:2181"
        resources: {}
      hostname: dev-kafka
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: dev-zookeeper
  name: dev-zookeeper
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    service: dev-zookeeper
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: dev-kafka
  name: dev-kafka
spec:
  selector:
    service: dev-kafka
  ports:
    - name: internal
      port: 29092
    - name: external
      port: 30092
      targetPort: 9092
  type: ClusterIP
